### ISSUE TITLE
Allow configuring date format for displayed events

### ISSUE THREAD

**Issue by agathauy** [coddingtonbear/obsidian-itinerary#9]

**Comment by agathauy** [comment]
Ok trying out this out, currently just added this in to stuff :D 


```                          
 const customDateOptions = {weekday: 'short'};

  dateStr.innerText = `${end.toLocaleString({...DateTime_1.DATE_FULL, ...customDateOptions})} (all day)`;
```

Btw great plugin! :D

**Comment by coddingtonbear** [comment]
So, an option is that we could update the `itinerary-event` node such that it accepted a "date format" to use for showing the displayed dates?  I think that kind of implementation might be just...

- Updating https://github.com/coddingtonbear/obsidian-itinerary/blob/8dfac297e20f82fa04cd61eca1678713122d4f8c/src/types.ts#L12 so that there was a parameter for the date format (maybe `dateFormat`?)
- Updating https://github.com/coddingtonbear/obsidian-itinerary/blob/8dfac297e20f82fa04cd61eca1678713122d4f8c/src/extractor.ts#L28 so that it checked for a provided format in `parsed` and if not, used whatever default is reasonable.
- Updating https://github.com/coddingtonbear/obsidian-itinerary/blob/8dfac297e20f82fa04cd61eca1678713122d4f8c/src/render.ts#L169 & other instances of `DateTime.DATE_FULL` to use that provided value.

If you wanted to post a PR working on something like this, I'd be glad to help you out sometime.

**Comment by coddingtonbear** [comment]
Definitely feel free to start a discussion via the "Discussions" panel if you're looking for somebody to implement this for you.  Cheers & good luck!
